// Generated by CoffeeScript 1.10.0
(function() {
  define(['app', 'jquery.jqGrid'], function(App) {
    var View, tableCtTpl;
    tableCtTpl = ['<div class="row">', '<div class="col-xs-12 jgrid-container">', '<table id="untitled-grid-table"></table>', '<div id="untitled-grid-pager" ></div>', '</div>', '</div>'].join('');
    View = Marionette.ItemView.extend({
      template: _.template(tableCtTpl),
      tabId: '',
      onRender: function() {
        var me;
        me = this;
        return _.defer(function() {
          return me.renderGrid();
        });
      },
      renderGrid: function() {
        var grid, me;
        me = this;
        return grid = App.Factory.createJqGrid({
          rsId: '',
          caption: '',
          nav: {
            actions: {
              search: false,
              add: false
            }
          },
          actionsCol: {
            edit: false,
            del: false
          },
          gid: 'untitled-grid',
          url: url._(''),
          colNames: {},
          colModel: []
        });
      }
    });
    return App.on('untitled:list', function() {
      return App.show(new View());
    });
  });

}).call(this);

//# sourceMappingURL=test.js.map
